"use client"
import { useEffect } from "react";
function BootstrapClient() {
useEffect(() => {
    require("bootstrap/dist/js/bootstrap.bundle.min.js");
}, []);
return null;
}
export default BootstrapClient;
Then edit the src/app/layout.tsx:
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import BootstrapClient from "@/components/BootstrapClient";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
title: "Create Next App",
description: "Generated by create next app",
};
export default function RootLayout({
children,
}: Readonly<{
children: React.ReactNode;
}>) {
return (
<html
lang="en">
<body
className={inter.className}>
<BootstrapClient />
{children}
</body>
</html>
);
}